/**
 * Generated by tsnapi — public API snapshot of `ts-content-mapper`
 */
// #region Interfaces
export interface CloseProjectParams {
  projectHandle: string;
}
export interface ContentMapperContext {
  positionEncoding: PositionEncoding;
  locale?: string;
  signal: AbortSignal;
}
export interface ContentMapperDefinition<Options = Record<string, unknown>, Project = undefined> {
  diagnosticSource: string;
  positionEncoding?: PositionEncoding;
  openProject?: (_: OpenProjectParams<Options>, _: ContentMapperContext) => Awaitable<OpenProjectHandlerResult<Project>>;
  transform: (_: TransformParams, _: ProjectContext<Project, Options>) => Awaitable<TransformResult>;
  closeProject?: (_: CloseProjectParams, _: ProjectContext<Project, Options>) => Awaitable<void>;
}
export interface ContentMapperDiagnostic {
  messageText: string;
  start: number;
  length: number;
  code: number;
}
export interface ContentMapperManifest {
  exec: [command: string, ...arguments_: string[]];
  compilerOptions?: string[];
  dynamicConfig?: boolean;
}
export interface DiagnosticDirectives {
  unusedExpectDirectiveDiagnostics: UnusedExpectDirectiveDiagnostic[];
  directives: MappedDiagnosticDirective[];
}
export interface InitializeParams {
  locale?: string;
  positionEncodings: PositionEncoding[];
}
export interface InitializeResult {
  positionEncoding: PositionEncoding;
  diagnosticSource: string;
}
export interface MappedCodeBuilderOptions {
  positionEncoding?: PositionEncoding;
}
export interface MappedOutput {
  text: string;
  extension: VirtualExtension;
  mappings?: SpanMapping[];
  diagnosticDirectives?: DiagnosticDirectives;
}
export interface OpenProjectParams<Options = Record<string, unknown>> {
  configFileName: string;
  projectHandle: string;
  options?: Options;
  compilerOptions: Record<string, unknown>;
}
export interface OpenProjectResult {
  configIdentity?: string;
  watchedFiles?: string[];
  optionDiagnostics?: OptionDiagnostic[];
}
export interface OptionDiagnostic {
  path: Array<string | number>;
  messageText: string;
  code: number;
}
export interface ProjectContext<Project, Options = Record<string, unknown>> extends ContentMapperContext {
  project: Project;
  openProjectParams: OpenProjectParams<Options>;
}
export interface RunContentMapperOptions {
  input?: NodeJS.ReadableStream;
  output?: NodeJS.WritableStream;
}
export interface RunningContentMapper {
  dispose: () => void;
}
export interface TransformParams {
  fileName: string;
  content: string;
  projectHandle: string;
}
export interface TransformResult extends MappedOutput {
  diagnostics?: ContentMapperDiagnostic[];
  supplemental?: MappedOutput[];
}
export interface UnusedExpectDirectiveDiagnostic {
  code: number;
  messageText: string;
}
// #endregion

// #region Types
export type DiagnosticDirectivePolicy = (typeof DiagnosticDirectivePolicy)[keyof typeof DiagnosticDirectivePolicy];
export type MappedDiagnosticDirective = readonly [originalStart: number, originalLength: number, virtualStart: number, virtualEnd: number, policy: DiagnosticDirectivePolicy, unusedExpectDirectiveIndex?: number];
export type PositionEncoding = "utf-8" | "utf-16";
export type SpanMapFeatures = number;
export type SpanMapKind = (typeof SpanMapKind)[keyof typeof SpanMapKind];
export type SpanMapping = readonly [virtualStart: number, virtualLength: number, originalStart: number, originalLength: number, kind: SpanMapKind, features?: SpanMapFeatures];
export type VirtualExtension = ".js" | ".jsx" | ".mjs" | ".cjs" | ".ts" | ".tsx" | ".mts" | ".cts" | ".json";
// #endregion

// #region Classes
export declare class MappedCodeBuilder {
  #private;
  readonly originalText: string;
  readonly positionEncoding: PositionEncoding;
  constructor(_: string, _?: MappedCodeBuilderOptions);
  get length(): number;
  get text(): string;
  append(_: string): this;
  appendVerbatim(_: number, _: number, _?: SpanMapFeatures): this;
  appendAtom(_: string, _: number, _: number, _?: SpanMapFeatures): this;
  appendAlias(_: string, _: number, _: number, _?: SpanMapFeatures): this;
  appendAnchored(_: string, _: number, _?: SpanMapFeatures): this;
  appendMapped(_: string, _: number, _: number, _?: AppendMappedOptions): this;
  build(_: VirtualExtension, _?: BuildMappedOutputOptions): MappedOutput;
}
// #endregion

// #region Functions
export declare function encodedLength(_: string, _: PositionEncoding): number;
export declare function runContentMapper<Options = Record<string, unknown>, Project = undefined>(_: ContentMapperDefinition<Options, Project>, _?: RunContentMapperOptions): RunningContentMapper;
export declare function stringIndexToPosition(_: string, _: number, _: PositionEncoding): number;
// #endregion

// #region Variables
export declare const SpanMapFeature: {
  readonly None: 0;
  readonly Hover: 1;
  readonly SignatureHelp: 2;
  readonly Completion: 4;
  readonly Definition: 8;
  readonly TypeDefinition: 16;
  readonly Implementation: 32;
  readonly References: 64;
  readonly DocumentHighlights: 128;
  readonly Rename: 256;
  readonly CallHierarchy: 512;
  readonly CodeActions: 1_024;
  readonly Formatting: 2_048;
  readonly InlayHints: 4_096;
  readonly SemanticTokens: 8_192;
  readonly FoldingRanges: 16_384;
  readonly SelectionRanges: 32_768;
  readonly LinkedEditing: 65_536;
  readonly AutoInsert: 131_072;
  readonly DocumentSymbols: 262_144;
  readonly CodeLens: 524_288;
  readonly All: 1_048_575;
};
// #endregion

// #region Referenced (internal)
interface AppendMappedOptions {
  kind?: SpanMapKind;
  features?: SpanMapFeatures;
}
type Awaitable<Value> = Value | PromiseLike<Value>;
interface BuildMappedOutputOptions {
  diagnosticDirectives?: DiagnosticDirectives;
}
type OpenProjectHandlerResult<Project> = OpenProjectResult & {
  project?: Project;
};
// #endregion